# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on:
  push:
    branches: [ "main", "UI" ]
  pull_request:
    branches: [ "main", "UI" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with: 
          {"flutter-version":'2.x'}

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze
  
      - name: Run tests
        run: flutter test
  
      - name: Build APK
        run: flutter build apk



