

name: Deploy to Firebase Hosting on merge (CD)
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
      - name: Get dependencies
        run: flutter pub get
      - name: Clean 
        run: flutter clean
      - name: Upgrade dependencies
        run: flutter upgrade
      - name: Run the application
      - run: flutter run
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SHIELDY_6E7A5 }}'
          channelId: live
          projectId: shieldy-6e7a5
